# Generated by Django 3.2.6 on 2021-08-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_memberprofile_workspaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='workspaces',
        ),
    ]
