# Generated by Django 3.2.6 on 2021-08-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_memberprofile_workspaces'),
        ('workspace', '0002_auto_20210829_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(through='workspace.WorkspaceMembers', to='profiles.MemberProfile'),
        ),
        migrations.AlterField(
            model_name='workspacemembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='profiles.memberprofile'),
        ),
        migrations.AlterField(
            model_name='workspacemembers',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='workspace.workspace'),
        ),
    ]
